menu:
  Home: /
  Archives: /archives

excerpt_link: Read More

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus: 112534829542182736280
twitter: fatteru
github: fatteru

fancybox: true
google_analytics: UA-41856711-1
rss: